name: scratch_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.4.0
  google_fonts: ^6.2.1
  card_swiper: ^3.0.1
  flutter_datetime_picker_plus: ^2.2.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1
  geolocator: ^11.1.0
  location: ^6.0.2
  google_maps_flutter: ^2.7.0
  geocoding: ^3.0.0
  web_socket_channel: ^3.0.1
  web_socket_client: ^0.1.4
  url_launcher: ^6.3.0
  # flutter_inappwebview: ^5.7.0
  # webview_flutter: ^4.8.0
  shimmer: ^3.0.0
  # spotify_sdk: ^3.0.0-dev.3
  # flutter_web_auth_2: ^3.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
